### ISSUE TITLE
Update base image to Ubuntu 16.04

### ISSUE THREAD

**Issue by Frenzie** [koreader/virdevenv#24]
Ubuntu 14.04 will cease to be supported in the near future, so it's time to start migrating. 

* Rebase kobase on phusion v0.10.2.

This will also fix the fact that openjdk-r/ppa no longer offers openjdk-8-jdk, since it's included in 16.04 by default. https://packages.ubuntu.com/xenial/openjdk-8-jdk

We'll also get newer gcc and newer git, which should fix up https://github.com/koreader/koreader-base/pull/675 with no additional effort.
https://packages.ubuntu.com/xenial/git

**Comment by NiLuJe** [comment]
Does Travis have an ETA for doing the same?

**Comment by Frenzie** [comment]
You can specify `dist: xenial` since https://github.com/travis-ci/travis-yml/pull/16 I believe.

I already discussed this change with @houqp half a year ago, who was quite enthusiastic about moving to newer gcc, btw. ;-)

My main stopper was a lack of time really, but today seemed like a nice day to get a few things out of the way.

Now if only Travis would quit glitching out today I could get on with it… :-D

**Comment by Frenzie** [comment]
See https://www.traviscistatus.com/incidents/7k1r5btfg45m?u=btrh4ggtksg6
