### ISSUE TITLE
I cant build Win32

### ISSUE THREAD

**Issue by gerroon** [koreader/virdevenv#4]
I am on Debian Testing. I installed all the dependencies in the host and the guest and got everything up an running as described in the readme.

./kodev build win32

<command-line>:0:0: note: this is the location of the previous definition
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.o
BUILDVM   lj_bcdef.h
BUILDVM   lj_ffdef.h
BUILDVM   lj_folddef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
CC        ljamalg.o
In file included from lj_obj.h:14:0,
                 from lj_gc.c:12,
                 from ljamalg.c:31:
lj_arch.h:515:0: warning: "LUAJIT_NO_LOG2" redefined [enabled by default]
 #define LUAJIT_NO_LOG2
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from lj_obj.h:14:0,
                 from lj_gc.c:12,
                 from ljamalg.c:31:
lj_arch.h:518:0: warning: "LUAJIT_NO_EXP2" redefined [enabled by default]
 #define LUAJIT_NO_EXP2
 ^
<command-line>:0:0: note: this is the location of the previous definition
DYNLINK   lua51.dll
/usr/bin/i686-w64-mingw32-strip:st0LUGGJ: Protocol error
make[7]: *** [lua51.dll] Error 1
make[7]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32/luajit-prefix/src/luajit/src'
make[6]: *** [amalg] Error 2
make[6]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32/luajit-prefix/src/luajit/src'
make[5]: *** [amalg] Error 2
make[5]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32/luajit-prefix/src/luajit'
make[4]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[4]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32'
make[3]: *** [CMakeFiles/luajit.dir/all] Error 2
make[3]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/vagrant/koreader/base/thirdparty/luajit/build/i686-w64-mingw32'
make[1]: *** [build/i686-w64-mingw32/luajit.exe] Error 2
make[1]: Leaving directory `/home/vagrant/koreader/base'
make: *** [base/build/i686-w64-mingw32/luajit] Error 2

**Comment by houqp** [comment]
If I remember it correctly, the windows build only works under windows.

**Comment by Frenzie** [comment]
Closing for now. :-)
