### ISSUE TITLE
Emulator on osx

### ISSUE THREAD

**Issue by z3t0** [koreader/virdevenv#5]
> If you want to run emulator from inside vm, make sure X window system is installed on host machine.

If I run ./kodev run from inside the vagrant ssh i get some garbled text in a terminal which I'm assuming is the emulator? 

I'm pretty sure I'm doing something wrong here, not sure what though.

**Comment by z3t0** [comment]
restarting the host fixed this.

**Comment by houqp** [comment]
next time it happens, you can try running the `rest` command in the terminal.

**Comment by z3t0** [comment]
Managed to fix this by ensuring that vagrant ssh was run from a terminal inside Xquartz on MacOS. That might be something to add to the README as it took a long time to figure out haha.

**Comment by Frenzie** [comment]
Could you stick it in a PR?
