### ISSUE TITLE
Failed to build kobo release

### ISSUE THREAD

**Issue by jperon** [koreader/virdevenv#55]
After issuing following commands (in the koreader folder):

```bash
docker run -v "${PWD}":/home/ko/koreader -it koreader/koappimage:latest bash
cd koreader
./kodev fetch-thirdparty
./kodev release kobo
```

Here is what I get:

```
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wnull-dereference’                                                                
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wduplicated-branches’                                                             
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wduplicated-cond’                                                                 
Makefile:122: recipe for target 'Release/openssh/atomicio.o' failed
make[3]: *** [Release/openssh/atomicio.o] Error 1
make[3]: *** Waiting for unfinished jobs....
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wnull-dereference’
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wduplicated-branches’
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wduplicated-cond’
Makefile:122: recipe for target 'Release/usbms.o' failed
make[3]: *** [Release/usbms.o] Error 1
make[3]: Leaving directory '/home/ko/koreader/base/thirdparty/kobo-usbms/build/arm-linux-gnueabihf/kobo-usbms-prefix/src/kobo-usbms'
Makefile:198: recipe for target 'release' failed
make[2]: *** [release] Error 2
make[2]: Leaving directory '/home/ko/koreader/base/thirdparty/kobo-usbms/build/arm-linux-gnueabihf/kobo-usbms-prefix/src/kobo-usbms'
ninja: build stopped: subcommand failed.
Makefile.third:514: recipe for target 'build/arm-linux-gnueabihf/data/KoboUSBMS.tar.gz' failed
make[1]: *** [build/arm-linux-gnueabihf/data/KoboUSBMS.tar.gz] Error 1
make[1]: Leaving directory '/home/ko/koreader/base'
Makefile:73: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by NiLuJe** [comment]
`arm-linux-gnueabihf-gcc`

That's the wrong toolchain, because that's the wrong docker image: I don't know the Kobo image name by heart, but you're using the AppImage one ;).

**Comment by jperon** [comment]
OK :) thanks!

**Comment by Frenzie** [comment]
> That's the wrong toolchain, because that's the wrong docker image: I don't know the Kobo image name by heart, but you're using the AppImage one (which means it's probably a crappy Ubuntu arm TC instead of our lovingly hand-crafted one ;p) ;).

Longer term I suppose I'll split out the Ubuntu TC into a separate Docker container. It's used for the Sony builds. I'm not really sure why it's in the base image; maybe it's just some houqp initial testing lefovers.

But the fact that it's a crappy Ubuntu TC as you put it probably doesn't matter that much. The Ubuntu TC will build it and it'll run (guilty as charged here…). The problem that output pasted above is presumably that it's Ubuntu 16.04 with gcc 5.3. Just a touch too old for some more recent changes.

**Comment by NiLuJe** [comment]
It's only the tip of the iceberg, though: it'll be built against a different glibc than the expected one, and the existing workarounds are limited to very old CodeSourcery/MentorGraphics toolchains, I can't vouch for an Ubuntu TC actually building usable binaries ;).

**Comment by Frenzie** [comment]
I can. ;-)

It's a perfectly usable lazy/low on disk space choice. Of course it's not ideal, and using the wrong *Docker* image is pretty silly because that's neither lazy nor saving disk space. xD
