### ISSUE TITLE
Can't build Koreader

### ISSUE THREAD

**Issue by mwoz123** [koreader/virdevenv#59]
What I did: 
```
git clone https://github.com/koreader/koreader.git
docker run -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash
cd koreader && ./kodev fetch-thirdparty
```
& then 
```
ko@a45def78362f:~/koreader$ ./kodev build
```
date: 
```
ko@a45def78362f:~/koreader$ date
Sun May 16 19:44:53 UTC 2021
```
log error: 

```
/bin/bash ../libtool  --tag=CXX   --mode=compile /usr/bin/ccache g++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG -DUSE_STD_NAMESPACE -I../cutil -I../ccutil -I../ccstruct -I../dict -I../ccmain -I../classify -I../textord -I../wordrec -I../neural_networks/runtime -I../viewer  -I/home/ko/koreader/base/thirdparty/leptonica/build/x86_64-linux-gnu-debug/leptonica-prefix/src/leptonica/src/.  -Og -g -pipe -fno-omit-frame-pointer  -std=gnu++11 -march=native -fPIC -O3 -MT char_set.lo -MD -MP -MF .deps/char_set.Tpo -c -o char_set.lo char_set.cpp
libtool: compile:  /usr/bin/ccache g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE -I../cutil -I../ccutil -I../ccstruct -I../dict -I../ccmain -I../classify -I../textord -I../wordrec -I../neural_networks/runtime -I../viewer -I/home/ko/koreader/base/thirdparty/leptonica/build/x86_64-linux-gnu-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -std=gnu++11 -march=native -fPIC -O3 -MT char_set.lo -MD -MP -MF .deps/char_set.Tpo -c char_set.cpp  -fPIC -DPIC -o .libs/char_set.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:83:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from string_32.h:28,
                 from char_samp.h:35,
                 from char_samp_enum.h:26,
                 from char_samp_enum.cpp:20:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘unsigned int _xbegin()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:52:33: error: ‘__builtin_ia32_xbegin’ was not declared in this scope
   return __builtin_ia32_xbegin ();
                                 ^
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘void _xend()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:63:24: error: ‘__builtin_ia32_xend’ was not declared in this scope
   __builtin_ia32_xend ();
                        ^
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘void _xabort(unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:73:29: error: ‘__builtin_ia32_xabort’ was not declared in this scope
   __builtin_ia32_xabort (imm);
                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:85:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from string_32.h:28,
                 from char_samp.h:35,
                 from char_samp_enum.h:26,
                 from char_samp_enum.cpp:20:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xtestintrin.h: In function ‘int _xtest()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xtestintrin.h:43:32: error: ‘__builtin_ia32_xtest’ was not declared in this scope
   return __builtin_ia32_xtest ();
                                ^
Makefile:547: recipe for target 'char_samp_enum.lo' failed
make[5]: *** [char_samp_enum.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:83:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from bmp_8.cpp:23:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘unsigned int _xbegin()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:52:33: error: ‘__builtin_ia32_xbegin’ was not declared in this scope
   return __builtin_ia32_xbegin ();
                                 ^
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘void _xend()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:63:24: error: ‘__builtin_ia32_xend’ was not declared in this scope
   __builtin_ia32_xend ();
                        ^
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h: In function ‘void _xabort(unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/rtmintrin.h:73:29: error: ‘__builtin_ia32_xabort’ was not declared in this scope
   __builtin_ia32_xabort (imm);
                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:85:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from bmp_8.cpp:23:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xtestintrin.h: In function ‘int _xtest()’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xtestintrin.h:43:32: error: ‘__builtin_ia32_xtest’ was not declared in this scope
   return __builtin_ia32_xtest ();
                                ^
Makefile:547: recipe for target 'bmp_8.lo' failed
make[5]: *** [bmp_8.lo] Error 1
mv -f .deps/char_samp_set.Tpo .deps/char_samp_set.Plo
mv -f .deps/altlist.Tpo .deps/altlist.Plo
mv -f .deps/char_bigrams.Tpo .deps/char_bigrams.Plo
mv -f .deps/char_altlist.Tpo .deps/char_altlist.Plo
mv -f .deps/char_samp.Tpo .deps/char_samp.Plo
mv -f .deps/beam_search.Tpo .deps/beam_search.Plo
mv -f .deps/char_set.Tpo .deps/char_set.Plo
make[5]: Leaving directory '/home/ko/koreader/base/thirdparty/tesseract/build/x86_64-linux-gnu-debug/tesseract-prefix/src/tesseract/cube'
Makefile:478: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/ko/koreader/base/thirdparty/tesseract/build/x86_64-linux-gnu-debug/tesseract-prefix/src/tesseract'
Makefile:387: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/ko/koreader/base/thirdparty/tesseract/build/x86_64-linux-gnu-debug/tesseract-prefix/src/tesseract'
Makefile:105: recipe for target 'libtesseract.so' failed
make[2]: *** [libtesseract.so] Error 2
make[2]: Leaving directory '/home/ko/koreader/base/thirdparty/libk2pdfopt/build/x86_64-linux-gnu-debug/libk2pdfopt-prefix/src/libk2pdfopt'
ninja: build stopped: subcommand failed.
Makefile.third:289: recipe for target 'build/x86_64-linux-gnu-debug/libs/libk2pdfopt.so.2' failed
make[1]: *** [build/x86_64-linux-gnu-debug/libs/libk2pdfopt.so.2] Error 1
make[1]: Leaving directory '/home/ko/koreader/base'
Makefile:121: recipe for target 'base/build/x86_64-linux-gnu-debug/luajit' failed
make: *** [base/build/x86_64-linux-gnu-debug/luajit] Error 2
Failed to build emulator! Try run with -v for more information.
ko@a45def78362f:~/koreader$ 
```

Isn't it the docker ubuntu 16.04 too old ? or it should work ?

my "real" OS :
```
marcin@hp:~/workspace$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by Frenzie** [comment]
> Isn't it the docker ubuntu 16.04 too old ? or it should work ?

Much more than that: these images are used every single day as well as on every PR.

This is definitely completely from scratch?

**Comment by NiLuJe** [comment]
Is it *really* supposed to be using a crappy GCC 5, though?

**Comment by Frenzie** [comment]
Yup, because I use 10.3 and chances are you use 11.1. Part of the CI's job is to ensure it'll keep working on older systems without too much effort.

But Ubuntu 16.04 reached EOL a few weeks back, so I'll upgrade it to 18.04 with what you'll call a crappy GCC 7.4 in the nearby future. ;-)

**Comment by Frenzie** [comment]
Anyway, I just ran this from scratch and as expected it works for me.

**Comment by mwoz123** [comment]
> This is definitely completely from scratch?

I'd say Yes, but can you explain what exaclty you mean by that? I'd a fresh new folder, on this laptop I belive I never develop/run koreade. I just ran the commands mentioned 1st post. Is there something more? 

Does it make any difference on my ubuntu I'm only updating to `security updates` (not 'normal/new feature' updates, so  have base ubuntu system functions are from Aprill 2020) ?


I did looked around on the docker and found `insstall_luarocks.sh` :
```
ko@fc74e3e4136a:~/koreader$ cd ..
ko@fc74e3e4136a:~$ ls
install_luarocks.sh  koreader  local
ko@fc74e3e4136a:~$ 
```
After running `install_luarocks.sh` , `kodev clean`, `fetch-thirdparty` & `build` - it seems I've move a step forward - it doesn't error on build. Yestarday I did tried same thing but without `install_luarocks` but I still have had the above error. 

Is this lua_rock install reuiqired for building? Maybe then it should be added to Readme.md ?
Anyway I'll try on my other PC when I've time..

```
[*] Version: v2021.04-79-gba00f38_2021-05-16

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
05/17/21-05:05:49 INFO  platform thirdparty apps
-> Goldendict (goldendict), role: dict, available: false

Starting SDL in /home/ko/koreader/base/build/x86_64-linux-gnu-debug/
./luajit: ./ffi/SDL2_0.lua:91: Cannot initialize SDL: Failed to connect to the Mir Server
stack traceback:
	[C]: in function 'error'
	./ffi/SDL2_0.lua:91: in function 'open'
	./ffi/framebuffer_SDL2_0.lua:13: in function 'init'
	./ffi/framebuffer.lua:125: in function 'new'
	frontend/device/sdl/device.lua:150: in function 'init'
	frontend/device.lua:53: in main chunk
	[C]: in function 'require'
	./reader.lua:142: in main chunk
	[C]: at 0x0040558e
~/koreader
ko@fc74e3e4136a:~/koreader$ 
```
same error for starting with my ubuntu 20.04: 
`marcin@hp:~/workspace$ docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash -c "source ~/.bashrc && pushd koreader && ./kodev run"`
results:
```
Starting SDL in /home/ko/koreader/base/build/x86_64-linux-gnu-debug/
./luajit: ./ffi/SDL2_0.lua:91: Cannot initialize SDL: Failed to connect to the Mir Server
stack traceback:
	[C]: in function 'error'
	./ffi/SDL2_0.lua:91: in function 'open'
	./ffi/framebuffer_SDL2_0.lua:13: in function 'init'
	./ffi/framebuffer.lua:125: in function 'new'
	frontend/device/sdl/device.lua:150: in function 'init'
	frontend/device.lua:53: in main chunk
	[C]: in function 'require'
	./reader.lua:142: in main chunk
	[C]: at 0x0040558e
~/koreader
marcin@hp:~/workspace$
```
why it wants Mir?

**Comment by Frenzie** [comment]
> I'd say Yes, but can you explain what exaclty you mean by that? I'd a fresh new folder, on this laptop I belive I never develop/run koreade. I just ran the commands mentioned 1st post. Is there something more?

Correct, a fresh folder is what I mean. As opposed to having first used the folder with your host system's GCC for example.

> Is this lua_rock install reuiqired for building? Maybe then it should be added to Readme.md ?

It's not required in the sense you're implying. It's part of the Docker image build process.
0
> why it wants Mir?

That means it's not forwarding the X server properly.

**Comment by mwoz123** [comment]
Recently I thought it's because I used docker from snap. But after removal & install from apt docker. 
The result is the same Mir error on both ubuntu 20.04 PC & laptop :( 
I've removed old koreader dir and re-cloned but again results with Mir error 
no idea what can be wrong :(

**Comment by Frenzie** [comment]
As an aside, Docker is more complicated than [just installing a few Ubuntu packages](https://github.com/koreader/koreader/blob/master/doc/Building.md#debianubuntu-and-derivates). It's not clear to me why you wish to use the Docker image instead, but it works for me on Ubuntu 18.04, 20.04, 21.04, Debian 10, and Debian 11.

Did you set up Docker properly? If you don't add yourself to the `docker` group you might have to run it with `sudo` for example to get all the features working. <https://docs.docker.com/engine/install/linux-postinstall/>

Another thought, is it possible that you're on Wayland or something and that XWayland doesn't support this use case?

```sh
$ echo $XDG_SESSION_TYPE
x11
```

vs

```sh
$ echo $XDG_SESSION_TYPE
wayland
```

**Comment by mwoz123** [comment]
> It's not clear to me why you wish to use the Docker image instead,

as "[`Docker is the preferred method for building KOReader (..)`](https://github.com/koreader/virdevenv#virtual-dev-environment-for-koreader)" I wanted to try it ;) 

Maybe I'm strange but I like to keep my system clean of dependencies ;) 

When you install any package on ubuntu is usually has few of dependencies  (which are usually orphaned  when you remove the previously installed package). Moreover having Btrfs & timeshift & timeshift-apt/btrfs I've to manually remove all the system snapshots (that contained that extra dependecies) to free up disc space.

That's why I wanted 

>Another thought, is it possible that you're on Wayland or something and that XWayland doesn't support this use case?
I'm on x11.

**Comment by Frenzie** [comment]
> But yes, I remember I'd run Koreader on previous ubuntu installs without docker without docker layer, I'll problalby fallback to that...

I said that because of this issue I double checked it works *in Docker* on those installations.

**Comment by Frenzie** [comment]
PS 
> which are usually orphaned when you remove the previously installed package

apt autoremove is your friend (sorry, on phone ;) )

**Comment by mwoz123** [comment]
[solved](https://github.com/koreader/virdevenv#virtual-dev-environment-for-koreader) :  by running (on apt docker)
`docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash -c "source ~/.bashrc && pushd koreader && ./kodev run"`

PS
>apt autoremove is your friend (sorry, on phone ;) )

yes, but that works only partial solution when you're using btrfs-snapshots :/

**Comment by Frenzie** [comment]
> solved : by running (on apt docker)

I'm not following. That's 100% identical to what you said didn't work for you?

**Comment by mwoz123** [comment]
It was for ubuntu snap store docker

**Comment by Frenzie** [comment]
You mean snap Docker didn't work and Docker from the Ubuntu repos or the official Docker repo did? Okay, that makes sense to me. :-) Docker probably isn't the kind of snap that's built with X sockets in mind; what I wrote in the README here is a bit of a hack after all.[1]

As an aside, you can also only build using the Docker image and run the program outside of it. `libsdl2` is probably the only dependency for that, and you don't even need that one if you build an AppImage. Incidentally, speaking of the AppImage, if you only want to play around in Lua land then downloading the prebuilt AppImage and extracting the resources with `--appimage-extract` is all you need.

[1]  "NB The following command assumes KOReader is harmless and partially breaks the regular Docker container isolation."

**Comment by roygbyte** [comment]
> Incidentally, speaking of the AppImage, if you only want to play around in Lua land then downloading the prebuilt AppImage and extracting the resources with `--appimage-extract` is all you need.

Can a release (for Kobo, ideally) be made from an AppImage?

**Comment by Frenzie** [comment]
You can edit Lua files, test them on desktop, and then copy them over to a device when done.

**Comment by NiLuJe** [comment]
Or just scp/rsync the delta to a device and test on device ;). (This is how I do most of everything, I don't keep an emu build, just a source tree. The only time I actually build something is when I'm working on the buildsystem itself ;)).

**Comment by roygbyte** [comment]
> You can edit Lua files, test them on desktop, and then copy them over to a device when done.

Imagine that... I was under the impression that frontend files, like plugins, had to be built or something. 

> Or just scp/rsync the delta to a device and test on device ;). (This is how I do most of everything, I don't keep an emu build, just a source tree. The only time I actually build something is when I'm working on the buildsystem itself ;)).

In keeping with this process, if I was working on a plugin, I would write the core inside of the source tree, run the static check to find errors on the code, and just copy the plugin folder over to the device to test?

**Comment by Frenzie** [comment]
> In keeping with this process, if I was working on a plugin, I would write the code inside of the source tree, run the static check to find errors on the code, and just copy the plugin folder over to the device to test?

And restart the program, yes.

**Comment by roygbyte** [comment]
Thanks for the help! [Here's what I have been building.](https://github.com/roygbyte/koweather) It's a little weather app. Kind of janky at the moment, owing to my limited Lua skill.

**Comment by Frenzie** [comment]
Cool! :+1: 

You can submit a PR in https://github.com/koreader/contrib if you like.
