### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Edo78** [koreader/virdevenv#72]
I'm having an issue while running the emulator directly from the docker container.

`docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash -c "source ~/.bashrc && pushd koreader && ./kodev run"`

The previous command stop with
```
install -d thirdparty/lua-Spore/build/x86_64-linux-gnu-debug
rm -f /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug/lua-Spore-prefix/src/lua-Spore/../lua-Spore-stamp/lua-Spore-build
rm -f build/x86_64-linux-gnu-debug/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec
cd thirdparty/lua-Spore/build/x86_64-linux-gnu-debug && \
        cmake  -G Ninja -DOUTPUT_DIR="/home/ko/koreader/base/build/x86_64-linux-gnu-debug" \
        -DLUA_SPORE_VER=0.3.1-1 -DLD="/usr/bin/ccache gcc" \
        -DCC="/usr/bin/ccache gcc" -DCFLAGS="-Og -g -pipe -fno-omit-frame-pointer   -march=native -fPIC -I/home/ko/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src" \
        -DLUAROCKS="luarocks" \
        -DLUA_INCDIR=""/home/ko/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src"" \
        -DLUA_LIBDIR=""/home/ko/koreader/base/build/x86_64-linux-gnu-debug/libs/"" \
         \
        /home/ko/koreader/base/thirdparty/lua-Spore && \
        /usr/bin/ninja 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug
[1/7] Performing download step for 'lua-Spore'
FAILED: lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-download 
cd /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug/lua-Spore-prefix/src && /usr/bin/cmake -P /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug/git_checkout/tmp/lua-Spore-gitclone-tags/0.3.3.cmake && /usr/bin/cmake -E touch /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug/lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-download
Cloning into 'lua-Spore'...
fatal: unable to access 'https://framagit.org/fperrad/lua-Spore/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Cloning into 'lua-Spore'...
fatal: unable to access 'https://framagit.org/fperrad/lua-Spore/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Cloning into 'lua-Spore'...
fatal: unable to access 'https://framagit.org/fperrad/lua-Spore/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
-- Had to git clone more than once:
            3 times.
CMake Error at /home/ko/koreader/base/thirdparty/lua-Spore/build/x86_64-linux-gnu-debug/git_checkout/tmp/lua-Spore-gitclone-tags/0.3.3.cmake:66 (message):
  Failed to clone repository: 'https://framagit.org/fperrad/lua-Spore'


ninja: build stopped: subcommand failed.
Makefile.third:678: recipe for target 'build/x86_64-linux-gnu-debug/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec' failed
make[1]: *** [build/x86_64-linux-gnu-debug/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec] Error 1
make[1]: Leaving directory '/home/ko/koreader/base'
Makefile:81: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build emulator! Try run with -v for more information.
```
I'm on Ubuntu 20.04.3 using docker 20.10.12, build e91ed57
Trying to open `https://framagit.org/fperrad/lua-Spore/` in my browser show no issue with the certificate.

**Comment by Frenzie** [comment]
Latest seems to be outdated. I'll investigate that later (maybe I never set
it up for automated build), but use 0.2.2 instead. See
https://github.com/koreader/virdevenv/pull/68

**Comment by Edo78** [comment]
Using image version 0.2.2 complete the build but I encountered the very same segmentation fault reported in issue #67

**Comment by Frenzie** [comment]
In that case I suppose I should just delete the "btw, you can also do this pretty cool but mostly useless thing" section from the README. ;-) As I wrote in the referenced issue, if you're on Debubuntu Docker is pretty much just a more difficult method way of doing the same thing.

**Comment by Edo78** [comment]
I'm on ubuntu, I'm a developer and I usually use docker for work because it's way easier to use an image than installing multiple, sometime conflicting, dependencies.

Obviously I'm not here to tell you what you have to support but if you have it on the repo and it's not working you should remove it or fix it or just accept that people will open the same issue ...

**Comment by Frenzie** [comment]
It works perfectly fine for me on Ubuntu 20.04.

**Comment by Frenzie** [comment]
The dependencies are listed here: https://github.com/koreader/koreader/blob/master/doc/Building.md#debianubuntu-and-derivates

```
sudo apt-get install build-essential git patch wget unzip \
gettext autoconf automake cmake libtool nasm ragel luarocks lua5.1 libsdl2-dev \
libssl-dev libffi-dev libsdl2-dev libc6-dev-i386 xutils-dev linux-libc-dev:i386 zlib1g:i386
```
Most of those you should have installed regardless.

This is meant to make life easier for people, but if it's occurred twice already, apparently unfortunately it doesn't. So yes, I have to remove it even though I think it's useful and cool.

**Comment by Frenzie** [comment]
I think it speaksfor itself that forwarding X11 to Docker is here be dragons territory.

Have you tried `--ipc=host`, breaking container isolation even more? Also worth trying might be https://github.com/mviereck/x11docker

**Comment by Frenzie** [comment]
It looks like the Docker cloud webhook is returning 403, and I can't find the auto-build configuration on Docker Hub anymore.

I'm guessing this was disabled at some point in the past year of so.

https://docs.docker.com/docker-hub/builds/
>  This feature requires a Docker subscription
>
> The Automated Builds feature is available for Docker Pro, Team, and Business users. Upgrade now to automatically build and push your images. If you are using automated builds for an open-source project, you can join our Open Source Community program to learn how Docker can support your project on Docker Hub.

Grmbl.
