### ISSUE TITLE
Add deb image

### ISSUE THREAD

**Issue by Frenzie** [koreader/virdevenv#95]
@benoit-pierre I think you proposed to add a new image(s) to generate the Debian packages, which would presumably be the base image plus these:

https://github.com/koreader/virdevenv/blob/6d191b8c968d15679b3ab3e4885f0ff884e16ea7/docker/ubuntu/baseimage-18.04/bootstrap.sh#L10-L12

We can probably drop armel @pazos?

**Comment by pazos** [comment]
yay, we can murder the arm softfloat target.

> add a new image(s) to generate the Debian packages

Ideally, with https://github.com/koreader/koreader/pull/9351 merged in, the same image should take care of building generic linux tarballs and use those to generate debian packages.

> which would presumably be the base image plus these

Make sure `xz` is available to compress the generic linux artifacts and `dpkg-deb` to generate the debian blobs.

also add `chrpath`. Not mandatory but used if found in https://github.com/koreader/koreader/blob/master/platform/debian/do_debian_package.sh#L107-L112

**Comment by benoit-pierre** [comment]
> Ideally, with https://github.com/koreader/koreader/pull/9351 merged in […]

Is it ready to be merged? (So I can test the image).

**Comment by pazos** [comment]
@benoit-pierre: I think I've tested all possible cross targets a couple of years ago. Recently just rebased and switched from gzip to xz.

I think it is ready to go (paired with https://github.com/koreader/koreader-base/pull/1504). Maybe you can give it a quick review and tell me if you think it is ok as is?

I mean mostly the two steps for each ABI

`LINUX_ARCH=arm64 ./kodev release linux`
`./platform/linux/do_debian_package.sh path_to.tar.xz`

**Comment by pazos** [comment]
done
